name: brush step

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '10 0 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests pytz pycryptodome
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          python3 main.py ${user} ${passwd} ${open_get_weather} ${area}

          
      - name: random cron
        run: |
          # 提取当前cron分钟数
          current_minute=$(grep -oP "(?<=- cron: ')\d+" .github/workflows/brush_step.yml)
          
          # 生成新分钟数（范围0-59），直到与当前不同
          new_minute=$((RANDOM % 60))
          while [ "$new_minute" -eq "$current_minute" ]; do
            new_minute=$((RANDOM % 60))
          done
              # 替换cron分钟数
          sed -i -E "s/(- cron: ')[0-9]+( [^[:space:]]+ \* \* \*')/\1$new_minute\2/g" .github/workflows/brush_step.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "random cron"
          git push origin master
